### PR TITLE
Add testenv attribute

### PR DESCRIPTION
**Pull request by s-weigand**
Thanks for the nice plugin, this is super useful when building docs or running pre-commit and saves quite some time ❤️ 

The only issue I have is the clunky adding of 'direct' to the env name which would result in things like `tox -e direct-docs`.
Thus having a `direct` attribute in the testsenv definition would be great, thus I went ahead and added that feature.

Also, since it looks like you migrated this repo from GitLab I added a GitHub workflow as CI ([demo run here](https://github.com/s-weigand/tox-direct/actions/runs/572492123)).
If you would be interested I could make it a CI-CD workflow, so you would just need to make a release on GitHub and the new version will be deployed to PiPy.

### CODE REVIEW

**Comment by obestwalter** [comment]
Hey @s-weigand - thanks for the PR. I am shocked to see that other people actually use this abomination that goes against the spirit of tox and all that is good and holy in CI :scream: (but using it for e.g. pre-commit which has its own env management is actually a good idea).

Having used this plugin myself now for almost two years exclusively in container contexts, It turns out that we never use the env name form `[testenv:bla-direct]` anyway, but instead always call with ``--direct`` or ``--direct-yolo``. I think it was a stupid idea to start with, so I would likely even throw that out, to keep the code simple. But why is the activation on the caller side not enough for you, if I may ask?

I remember dimly that when I created this, I explicitly didn't want to add a keyword, but I think this was because I thought that tox should fail, when it encounters unknown keywords. It doesn't though and likely never will. Which means, what you propose could be added, and the same idea of graceful degradation still applies.

Thank you also for adding a GH action - you are right, this was first in a gitlab repo and I never bothered to update the CI settings. 

If you are determined to add this: the PR as it is, is a bit too comprehensive for me though and also contains parts that I wouldn't want to merge (https://github.com/obestwalter/tox-direct/pull/3/commits/fbf18f93f5b64575b41d6608333ed5f7e6ed83de - for me those ignores belong into the personal `.gitignore` of the developer and not into the project). Reformatting with black is something that can be done later by adding a pre-commit lint env. That could also be a tox direct env then, so this thing can test itself a bit here :) 

I haven't checked in detail yet, but I also think that the yolo part is missing on the keyword side then. As yolo is so fringe and dangerous I would propose that the direct keyword accepts True / False / YOLO (case insensitive) to have the same functionality like on the command line and having this dangerous option a bit more hidden than having an extra keyword for it.

So instead of this PR, I would appreciate two more focussed PRs - one for the GH action and the other one for the new feature. The rest should be left out (ignores and reformatting) for now.

**Comment by s-weigand** [comment]
Okidoki 2 Pr's it is 😄

TBH I kinda abuse `tox` for some things where the python version doesn't matter too much as a coss platform make (`pre-commit`, `docs` etc. ), just as an 'ok everything works! ready for the PR' gimmick. And today I came across some error with `sphinx` and `notebooks` where it failed to resolve the path for images when run with `tox`. So before digging deeper into this issue (is it a `sphinx` or notebook plugin problem?) I was looking for a hotfix and found your plugin which is perfect for my abuse cases and saves a lot of time.

When I started to work on this PR, I also added a `direct-yolo` attribute, to mirror the flags.
But then I thought "wait, there isn't a `direct-yolo` env naming pattern, there must be a reason" 🤔 
And I saw there is, maybe not on purpose, but still 😛.
E.g. (at least for me) a common pattern when contributing to a new project is, that when it uses `tox` you would fork and clone the repo, start a new venv and run tox to check if everything works out of the box or if you would need to configure something else. If a `yolo env` was in the tox config this might damage the host system.
Thus IMHO the YOLO should be reserved for explicit calls only, to save contributors from yolo abusers.

**Comment by s-weigand** [comment]
Ahhh and for the `.gitignore` issue.
IMHO it is more beginner-friendly to have an extensive `.gitignore` with all the things that don't belong in the repo.
I still remember my first time accidentally committing something I didn't want to and having to figure how to remove it w/o polluting the history with loads of revert commits and an already angry maintainer about me being a noob, committing it in the first place. 
Just my unasked 2 cents on that topic😛

**Comment by obestwalter** [comment]
> Thus IMHO the YOLO should be reserved for explicit calls only, to save contributors from yolo abusers.

Definitely. I mean the whole plugin is something that shouldn't exist according to some people ;) - but it fills a very particular gap in certain situations and I thought I might as well share it, but don't expect (or even hope for) this to ever being in wide use. I also use tox for pretty much all kinds of automation tasks and sometimes an extra venv is just unnecessary overhead and sometimes it is really necessary to use the host venv (in certain special container based setups.

> IMHO it is more beginner-friendly to have an extensive .gitignore with all the things that don't belong in the repo.

That might be, but this project is definitely not targeted to beginners anyway. I also think that participating in FOSS is a good way to learn how to do things better, so I would rather help beginners sort their problems out due to a botched commit and show them how they can avoid it in the future, rather than uselessly proliferating frankenstein/kitchensink .gitignore files.

You marked this as work in progress - let me know, when you think it's ready to merge and I'll integrate your changes.

**Comment by obestwalter** [comment]
... ehm I mean I guess, you'll close this one and you open a new one then :)

**Comment by s-weigand** [comment]
Yeah changing it to a Draft was just as a quick marking for "do not merge". 😉

**Pull request closed without merging**
